version: '3'
services:
  payment:
    build:
      dockerfile: Dockerfile
      context: ./payment
    ports:
      - '5000:5000'
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - '3000:3000'